
package com.wbd.dorayakisupplier.service;

import com.wbd.dorayakisupplier.ObjectFactory;
import com.wbd.dorayakisupplier.model.Request;
import com.wbd.dorayakisupplier.request.GetRequestsRequest;
import com.wbd.dorayakisupplier.response.GetRecipesResponse;
import com.wbd.dorayakisupplier.response.GetRequestsResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "DorayakiSupplierService", targetNamespace = "http://dorastore.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface DorayakiSupplierService {


    /**
     *
     * @return
     *     returns com.wbd.dorayakisupplier.GetRecipesResponse
     */
    @WebMethod(action = "http://dorastore.com/DorayakiSupplierService/getRecipes")
    @WebResult(name = "getRecipesResponse", targetNamespace = "http://dorastore.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetRecipesResponse getRecipes();

    /**
     *
     * @param parameters
     * @return
     *     returns com.wbd.dorayakisupplier.GetRequestsResponse
     */
    @WebMethod(action = "http://dorastore.com/DorayakiSupplierService/getRequests")
    @WebResult(name = "getRequestsResponse", targetNamespace = "http://dorastore.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetRequestsResponse getRequests(
            @WebParam(name = "getRequestsRequest", targetNamespace = "http://dorastore.com/", partName = "parameters")
                    GetRequestsRequest parameters);

    /**
     *
     * @param quantity
     * @param code
     * @param data
     * @param message
     * @param recipeId
     */
    @WebMethod(action = "http://dorastore.com/DorayakiSupplierService/restockRequest")
    @RequestWrapper(localName = "restockRequest", targetNamespace = "http://dorastore.com/", className = "com.wbd.dorayakisupplier.request.RestockRequest")
    @ResponseWrapper(localName = "messageResponse", targetNamespace = "http://dorastore.com/", className = "com.wbd.dorayakisupplier.response.MessageResponse")
    public void restockRequest(
            @WebParam(name = "recipeId", targetNamespace = "")
                    int recipeId,
            @WebParam(name = "quantity", targetNamespace = "")
                    int quantity,
            @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Integer> code,
            @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<String> message,
            @WebParam(name = "data", targetNamespace = "", mode = WebParam.Mode.OUT)
                    Holder<Request> data);

}
